<?php

namespace Database\Seeders;

use App\Models\Perfume;
use Illuminate\Database\Seeder;
use App\Enums\PerfumeGender;

class PerfumeSeeder extends Seeder
{
    public function run()
    {
        $perfumes = [
            [
                'name' => '01',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => 'Versace - Eros',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Desire',
                'accords' => [
                    ['name' => '5', 'percentage' => 50],
                    ['name' => '6', 'percentage' => 45],
                    ['name' => '7', 'percentage' => 42],
                    ['name' => '8', 'percentage' => 40],
                    ['name' => '1', 'percentage' => 39],
                    ['name' => '9', 'percentage' => 38],
                    ['name' => '3', 'percentage' => 37],
                    ['name' => '0', 'percentage' => 36],
                    ['name' => '10', 'percentage' => 35],
                    ['name' => '11', 'percentage' => 34],
                ],
            ],
            [
                'name' => '02',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => 'Lancome - La Vie Est Belle',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Eclat',
                'accords' => [
                    ['name' => '10', 'percentage' => 50],
                    ['name' => '5', 'percentage' => 48],
                    ['name' => '9', 'percentage' => 42],
                    ['name' => '12', 'percentage' => 39],
                    ['name' => '0', 'percentage' => 38],
                    ['name' => '13', 'percentage' => 37],
                    ['name' => '14', 'percentage' => 36],
                    ['name' => '15', 'percentage' => 35],
                    ['name' => '16', 'percentage' => 34],
                    ['name' => '17', 'percentage' => 33],
                ],
            ],
            [
                'name' => '03',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => 'Giorgio Armani - Code',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Cipher',
                'accords' => [
                    ['name' => '3', 'percentage' => 50],
                    ['name' => '37', 'percentage' => 42],
                    ['name' => '25', 'percentage' => 40],
                    ['name' => '26', 'percentage' => 39],
                    ['name' => '2', 'percentage' => 38],
                    ['name' => '42', 'percentage' => 37],
                    ['name' => '10', 'percentage' => 36],
                    ['name' => '6', 'percentage' => 35],
                    ['name' => '5', 'percentage' => 34],
                    ['name' => '21', 'percentage' => 33],
                ],
            ],
            [
                'name' => '04',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => 'Chanel - Coco',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Noire',
                'accords' => [
                    ['name' => '1', 'percentage' => 50],
                    ['name' => '17', 'percentage' => 46],
                    ['name' => '10', 'percentage' => 44],
                    ['name' => '14', 'percentage' => 39],
                    ['name' => '0', 'percentage' => 38],
                    ['name' => '5', 'percentage' => 37],
                    ['name' => '20', 'percentage' => 36],
                    ['name' => '13', 'percentage' => 35],
                    ['name' => '2', 'percentage' => 34],
                    ['name' => '21', 'percentage' => 33],
                ],
            ],
            [
                'name' => '05',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => 'Dior - Sauvage',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Raw',
                'accords' => [
                    ['name' => '8', 'percentage' => 55],
                    ['name' => '1', 'percentage' => 46],
                    ['name' => '3', 'percentage' => 44],
                    ['name' => '6', 'percentage' => 39],
                    ['name' => '23', 'percentage' => 38],
                    ['name' => '0', 'percentage' => 37],
                    ['name' => '22', 'percentage' => 36],
                    ['name' => '24', 'percentage' => 35],
                    ['name' => '17', 'percentage' => 34],
                ],
            ],
            [
                'name' => '06',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => 'Chanel - Gabrielle Essence',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Essenza',
                'accords' => [
                    ['name' => '13', 'percentage' => 60],
                    ['name' => '3', 'percentage' => 46],
                    ['name' => '9', 'percentage' => 44],
                    ['name' => '10', 'percentage' => 39],
                    ['name' => '0', 'percentage' => 38],
                    ['name' => '27', 'percentage' => 37],
                    ['name' => '28', 'percentage' => 36],
                    ['name' => '21', 'percentage' => 35],
                    ['name' => '14', 'percentage' => 34],
                    ['name' => '11', 'percentage' => 33],
                ],
            ],
            [
                'name' => '07',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => 'Emporio Armani - Stronger With You',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Bond',
                'accords' => [
                    ['name' => '5', 'percentage' => 60],
                    ['name' => '10', 'percentage' => 46],
                    ['name' => '30', 'percentage' => 44],
                    ['name' => '29', 'percentage' => 39],
                    ['name' => '6', 'percentage' => 38],
                    ['name' => '14', 'percentage' => 37],
                    ['name' => '22', 'percentage' => 36],
                    ['name' => '24', 'percentage' => 35],
                    ['name' => '26', 'percentage' => 34],
                    ['name' => '17', 'percentage' => 34],
                ],
            ],
            [
                'name' => '08',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => 'Chanel - Coco Mademoiselle',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Bovary',
                'accords' => [
                    ['name' => '3', 'percentage' => 60],
                    ['name' => '0', 'percentage' => 46],
                    ['name' => '12', 'percentage' => 44],
                    ['name' => '10', 'percentage' => 39],
                    ['name' => '13', 'percentage' => 38],
                    ['name' => '20', 'percentage' => 37],
                    ['name' => '16', 'percentage' => 36],
                    ['name' => '5', 'percentage' => 36],
                    ['name' => '17', 'percentage' => 36],
                    ['name' => '28', 'percentage' => 36],
                ],
            ],
            [
                'name' => '09',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Prada L'Homme L'Eau",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Pure',
                'accords' => [
                    ['name' => '14', 'percentage' => 55],
                    ['name' => '15', 'percentage' => 44],
                    ['name' => '0', 'percentage' => 42],
                    ['name' => '8', 'percentage' => 39],
                    ['name' => '19', 'percentage' => 38],
                    ['name' => '11', 'percentage' => 37],
                    ['name' => '3', 'percentage' => 36],
                    ['name' => '16', 'percentage' => 36],
                ],
            ],
            [
                'name' => '10',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => 'Narciso Rodriguez - For Her',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Muse',
                'accords' => [
                    ['name' => '23', 'percentage' => 60],
                    ['name' => '14', 'percentage' => 46],
                    ['name' => '13', 'percentage' => 44],
                    ['name' => '3', 'percentage' => 39],
                    ['name' => '2', 'percentage' => 38],
                    ['name' => '9', 'percentage' => 37],
                    ['name' => '0', 'percentage' => 36],
                    ['name' => '1', 'percentage' => 36],
                    ['name' => '21', 'percentage' => 36],
                    ['name' => '10', 'percentage' => 36],
                ],
            ],
            [
                'name' => '11',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Jean Paul Gaultier - Le Male",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Icon',
                'accords' => [
                    ['name' => '6', 'percentage' => 55],
                    ['name' => '5', 'percentage' => 52],
                    ['name' => '8', 'percentage' => 42],
                    ['name' => '22', 'percentage' => 39],
                    ['name' => '17', 'percentage' => 38],
                    ['name' => '7', 'percentage' => 37],
                    ['name' => '14', 'percentage' => 36],
                    ['name' => '10', 'percentage' => 36],
                    ['name' => '1', 'percentage' => 35],
                    ['name' => '0', 'percentage' => 35],
                ],
            ],
            [
                'name' => '12',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => 'Carolina Herrera - Good Girl',
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Velvet',
                'accords' => [
                    ['name' => '10', 'percentage' => 55],
                    ['name' => '13', 'percentage' => 52],
                    ['name' => '17', 'percentage' => 48],
                    ['name' => '5', 'percentage' => 47],
                    ['name' => '1', 'percentage' => 38],
                    ['name' => '31', 'percentage' => 37],
                    ['name' => '0', 'percentage' => 36],
                    ['name' => '27', 'percentage' => 36],
                    ['name' => '32', 'percentage' => 36],
                    ['name' => '14', 'percentage' => 35],
                ],
            ],
            [
                'name' => '13',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Montblanc – Legend",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Legacy',
                'accords' => [
                    ['name' => '9', 'percentage' => 55],
                    ['name' => '10', 'percentage' => 52],
                    ['name' => '6', 'percentage' => 42],
                    ['name' => '22', 'percentage' => 39],
                    ['name' => '8', 'percentage' => 38],
                    ['name' => '3', 'percentage' => 37],
                    ['name' => '0', 'percentage' => 36],
                    ['name' => '5', 'percentage' => 36],
                    ['name' => '24', 'percentage' => 35],
                    ['name' => '11', 'percentage' => 35],
                ],
            ],
            [
                'name' => '14',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => "Givenchy - L'Interdit",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Interdit',
                'accords' => [
                    ['name' => '13', 'percentage' => 55],
                    ['name' => '27', 'percentage' => 45],
                    ['name' => '10', 'percentage' => 38],
                    ['name' => '3', 'percentage' => 47],
                    ['name' => '0', 'percentage' => 38],
                    ['name' => '12', 'percentage' => 37],
                    ['name' => '5', 'percentage' => 36],
                    ['name' => '9', 'percentage' => 36],
                    ['name' => '21', 'percentage' => 36],
                ],
            ],
            [
                'name' => '15',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Giorgio Armani - Acqua di Gio Profondo",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Abyss',
                'accords' => [
                    ['name' => '33', 'percentage' => 55],
                    ['name' => '6', 'percentage' => 52],
                    ['name' => '3', 'percentage' => 42],
                    ['name' => '8', 'percentage' => 39],
                    ['name' => '11', 'percentage' => 38],
                    ['name' => '0', 'percentage' => 37],
                    ['name' => '49', 'percentage' => 36],
                    ['name' => '36', 'percentage' => 36],
                    ['name' => '22', 'percentage' => 35],
                ],
            ],
            [
                'name' => '16',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => "Mugler - Alien",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Aura',
                'accords' => [
                    ['name' => '13', 'percentage' => 60],
                    ['name' => '1', 'percentage' => 48],
                    ['name' => '2', 'percentage' => 38],
                    ['name' => '21', 'percentage' => 37],
                    ['name' => '14', 'percentage' => 37],
                ],
            ],
            [
                'name' => '17',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Prada - Luna Rossa",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Rossa',
                'accords' => [
                    ['name' => '6', 'percentage' => 55],
                    ['name' => '22', 'percentage' => 52],
                    ['name' => '7', 'percentage' => 42],
                    ['name' => '8', 'percentage' => 39],
                    ['name' => '3', 'percentage' => 38],
                    ['name' => '23', 'percentage' => 37],
                    ['name' => '1', 'percentage' => 36],
                    ['name' => '2', 'percentage' => 36],
                ],
            ],
            [
                'name' => '18',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => "Yves Saint Laurent - Black Opium",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Obscura',
                'accords' => [
                    ['name' => '13', 'percentage' => 60],
                    ['name' => '1', 'percentage' => 48],
                    ['name' => '2', 'percentage' => 38],
                    ['name' => '21', 'percentage' => 37],
                    ['name' => '14', 'percentage' => 37],
                ],
            ],
            [
                'name' => '19',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Creed - Aventus",
                'price' => 80,
                'discount_percentage' => null,
                'base_price' => 40,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Ascend',
                'accords' => [
                    ['name' => '9', 'percentage' => 55],
                    ['name' => '10', 'percentage' => 45],
                    ['name' => '0', 'percentage' => 44],
                    ['name' => '37', 'percentage' => 42],
                    ['name' => '3', 'percentage' => 41],
                    ['name' => '34', 'percentage' => 40],
                    ['name' => '23', 'percentage' => 39],
                    ['name' => '38', 'percentage' => 38],
                    ['name' => '11', 'percentage' => 38],
                    ['name' => '39', 'percentage' => 36],
                ],
            ],
            [
                'name' => '20',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => "Yves Saint Laurent - Libre",
                'price' => 80,
                'discount_percentage' => null,
                'base_price' => 40,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Liberte',
                'accords' => [
                    ['name' => '13', 'percentage' => 60],
                    ['name' => '3', 'percentage' => 48],
                    ['name' => '22', 'percentage' => 42],
                    ['name' => '5', 'percentage' => 40],
                    ['name' => '6', 'percentage' => 39],
                    ['name' => '10', 'percentage' => 38],
                    ['name' => '14', 'percentage' => 37],
                    ['name' => '21', 'percentage' => 36],
                    ['name' => '23', 'percentage' => 35],
                    ['name' => '0', 'percentage' => 34],
                ],
            ],
            [
                'name' => '21',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Louis Vuitton - L'Immensite",
                'price' => 100,
                'discount_percentage' => null,
                'base_price' => 50,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Infinite',
                'accords' => [
                    ['name' => '8', 'percentage' => 50],
                    ['name' => '3', 'percentage' => 45],
                    ['name' => '6', 'percentage' => 44],
                    ['name' => '1', 'percentage' => 42],
                    ['name' => '11', 'percentage' => 40],
                    ['name' => '35', 'percentage' => 37],
                    ['name' => '24', 'percentage' => 36],
                    ['name' => '23', 'percentage' => 35],
                ],
            ],
            [
                'name' => '22',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => "Jean Paul Gaultier - Divine",
                'price' => 80,
                'discount_percentage' => null,
                'base_price' => 40,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Celeste',
                'accords' => [
                    ['name' => '13', 'percentage' => 60],
                    ['name' => '10', 'percentage' => 48],
                    ['name' => '35', 'percentage' => 42],
                    ['name' => '33', 'percentage' => 40],
                    ['name' => '14', 'percentage' => 39],
                    ['name' => '6', 'percentage' => 38],
                    ['name' => '28', 'percentage' => 37],
                    ['name' => '36', 'percentage' => 36],
                    ['name' => '23', 'percentage' => 35],
                    ['name' => '0', 'percentage' => 34],
                ],
            ],
            [
                'name' => '23',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Nasamotto - Black Afgano",
                'price' => 100,
                'discount_percentage' => null,
                'base_price' => 50,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Resin',
                'accords' => [
                    ['name' => '1', 'percentage' => 55],
                    ['name' => '34', 'percentage' => 45],
                    ['name' => '0', 'percentage' => 44],
                    ['name' => '40', 'percentage' => 42],
                    ['name' => '41', 'percentage' => 40],
                    ['name' => '30', 'percentage' => 39],
                    ['name' => '7', 'percentage' => 38],
                    ['name' => '6', 'percentage' => 37],
                    ['name' => '17', 'percentage' => 36],
                    ['name' => '42', 'percentage' => 35],
                ],
            ],
            [
                'name' => '24',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => "Prada - Paradoxe",
                'price' => 100,
                'discount_percentage' => null,
                'base_price' => 50,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Paradox',
                'accords' => [
                    ['name' => '13', 'percentage' => 55],
                    ['name' => '3', 'percentage' => 48],
                    ['name' => '1', 'percentage' => 40],
                    ['name' => '10', 'percentage' => 40],
                    ['name' => '5', 'percentage' => 39],
                    ['name' => '14', 'percentage' => 38],
                    ['name' => '9', 'percentage' => 37],
                    ['name' => '23', 'percentage' => 36],
                    ['name' => '11', 'percentage' => 35],
                ],
            ],
            [
                'name' => '25',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Parfums de Marly - Pegasus Exclusif",
                'price' => 120,
                'discount_percentage' => null,
                'base_price' => 60,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Obsidian',
                'accords' => [
                    ['name' => '0', 'percentage' => 55],
                    ['name' => '32', 'percentage' => 54],
                    ['name' => '5', 'percentage' => 51],
                    ['name' => '14', 'percentage' => 42],
                    ['name' => '17', 'percentage' => 40],
                    ['name' => '40', 'percentage' => 39],
                    ['name' => '6', 'percentage' => 38],
                    ['name' => '10', 'percentage' => 37],
                    ['name' => '29', 'percentage' => 36],
                    ['name' => '8', 'percentage' => 35],
                ],
            ],
            [
                'name' => '26',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => "Parfums de Marley - Valaya",
                'price' => 120,
                'discount_percentage' => null,
                'base_price' => 60,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Ivoria',
                'accords' => [
                    ['name' => '23', 'percentage' => 55],
                    ['name' => '3', 'percentage' => 52],
                    ['name' => '13', 'percentage' => 40],
                    ['name' => '11', 'percentage' => 40],
                    ['name' => '18', 'percentage' => 39],
                    ['name' => '14', 'percentage' => 38],
                    ['name' => '9', 'percentage' => 37],
                    ['name' => '1', 'percentage' => 36],
                    ['name' => '0', 'percentage' => 35],
                    ['name' => '10', 'percentage' => 35],
                ],
            ],
            [
                'name' => '27',
                'gender' => PerfumeGender::MALE,
                'inspired_by' => "Louis Vuitton - Imagination",
                'price' => 120,
                'discount_percentage' => null,
                'base_price' => 60,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Vision',
                'accords' => [
                    ['name' => '3', 'percentage' => 55],
                    ['name' => '8', 'percentage' => 42],
                    ['name' => '11', 'percentage' => 40],
                    ['name' => '7', 'percentage' => 39],
                    ['name' => '1', 'percentage' => 38],
                ],
            ],
            [
                'name' => '28',
                'gender' => PerfumeGender::FEMALE,
                'inspired_by' => "Kilian - Love Don't be Shy",
                'price' => 150,
                'discount_percentage' => null,
                'base_price' => 75,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Blush',
                'accords' => [
                    ['name' => '10', 'percentage' => 55],
                    ['name' => '13', 'percentage' => 52],
                    ['name' => '5', 'percentage' => 42],
                    ['name' => '3', 'percentage' => 40],
                    ['name' => '43', 'percentage' => 39],
                    ['name' => '14', 'percentage' => 38],
                    ['name' => '23', 'percentage' => 37],
                    ['name' => '21', 'percentage' => 36],
                ],
            ],
            [
                'name' => '100',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Tiziana Terenzi - Kirke",
                'price' => 60,
                'discount_percentage' => null,
                'base_price' => 30,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Myth',
                'accords' => [
                    ['name' => '9', 'percentage' => 55],
                    ['name' => '10', 'percentage' => 45],
                    ['name' => '23', 'percentage' => 39],
                    ['name' => '14', 'percentage' => 38],
                    ['name' => '11', 'percentage' => 38],
                    ['name' => '38', 'percentage' => 37],
                    ['name' => '0', 'percentage' => 36],
                ],
            ],
            [
                'name' => '101',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Mancera - Red Tobacco",
                'price' => 80,
                'discount_percentage' => null,
                'base_price' => 40,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Redemption',
                'accords' => [
                    ['name' => '17', 'percentage' => 55],
                    ['name' => '42', 'percentage' => 52],
                    ['name' => '0', 'percentage' => 45],
                    ['name' => '10', 'percentage' => 42],
                    ['name' => '1', 'percentage' => 40],
                    ['name' => '5', 'percentage' => 39],
                    ['name' => '45', 'percentage' => 38],
                    ['name' => '40', 'percentage' => 37],
                    ['name' => '14', 'percentage' => 37],
                    ['name' => '8', 'percentage' => 36],
                ],
            ],
            [
                'name' => '102',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Giardini Di Toscana - Bianco Latte",
                'price' => 80,
                'discount_percentage' => null,
                'base_price' => 40,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Soie',
                'accords' => [
                    ['name' => '5', 'percentage' => 55],
                    ['name' => '10', 'percentage' => 52],
                    ['name' => '43', 'percentage' => 45],
                    ['name' => '46', 'percentage' => 42],
                    ['name' => '30', 'percentage' => 40],
                    ['name' => '14', 'percentage' => 39],
                    ['name' => '23', 'percentage' => 38],
                    ['name' => '6', 'percentage' => 37],
                    ['name' => '0', 'percentage' => 37],
                ],
            ],
            [
                'name' => '103',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Al Haramain - Amber Oud",
                'price' => 100,
                'discount_percentage' => null,
                'base_price' => 50,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Amberia',
                'accords' => [
                    ['name' => '0', 'percentage' => 55],
                    ['name' => '1', 'percentage' => 52],
                    ['name' => '6', 'percentage' => 45],
                    ['name' => '8', 'percentage' => 42],
                    ['name' => '3', 'percentage' => 40],
                    ['name' => '17', 'percentage' => 39],
                    ['name' => '14', 'percentage' => 38],
                    ['name' => '23', 'percentage' => 37],
                ],
            ],
            [
                'name' => '104',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Maison Francis Kurkdjian - Baccarat Rouge 540",
                'price' => 100,
                'discount_percentage' => null,
                'base_price' => 50,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Crimson',
                'accords' => [
                    ['name' => '0', 'percentage' => 55],
                    ['name' => '1', 'percentage' => 54],
                    ['name' => '17', 'percentage' => 45],
                    ['name' => '47', 'percentage' => 39],
                    ['name' => '8', 'percentage' => 38],
                    ['name' => '6', 'percentage' => 38],
                    ['name' => '13', 'percentage' => 38],
                    ['name' => '21', 'percentage' => 37],
                    ['name' => '11', 'percentage' => 37],
                ],
            ],
            [
                'name' => '105',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Xerjoff - 1861 Naxos",
                'price' => 100,
                'discount_percentage' => null,
                'base_price' => 50,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Aureum',
                'accords' => [
                    ['name' => '10', 'percentage' => 55],
                    ['name' => '46', 'percentage' => 50],
                    ['name' => '5', 'percentage' => 49],
                    ['name' => '42', 'percentage' => 39],
                    ['name' => '22', 'percentage' => 38],
                    ['name' => '3', 'percentage' => 38],
                    ['name' => '6', 'percentage' => 38],
                    ['name' => '2', 'percentage' => 37],
                    ['name' => '14', 'percentage' => 37],
                    ['name' => '17', 'percentage' => 36],
                ],
            ],
            [
                'name' => '106',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Matiere Premiere - Vanilla Powder",
                'price' => 100,
                'discount_percentage' => null,
                'base_price' => 50,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Velours',
                'accords' => [
                    ['name' => '5', 'percentage' => 55],
                    ['name' => '14', 'percentage' => 47],
                    ['name' => '23', 'percentage' => 44],
                    ['name' => '0', 'percentage' => 39],
                    ['name' => '10', 'percentage' => 38],
                    ['name' => '48', 'percentage' => 37],
                    ['name' => '3', 'percentage' => 36],
                ],
            ],
            [
                'name' => '107',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Marc-Antoine Barrois - Ganymede",
                'price' => 120,
                'discount_percentage' => null,
                'base_price' => 60,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Jupiter',
                'accords' => [
                    ['name' => '49', 'percentage' => 55],
                    ['name' => '17', 'percentage' => 50],
                    ['name' => '37', 'percentage' => 48],
                    ['name' => '0', 'percentage' => 39],
                    ['name' => '40', 'percentage' => 38],
                    ['name' => '23', 'percentage' => 38],
                    ['name' => '47', 'percentage' => 38],
                    ['name' => '2', 'percentage' => 37],
                    ['name' => '14', 'percentage' => 37],
                    ['name' => '9', 'percentage' => 36],
                ],
            ],
            [
                'name' => '108',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Orto Parisi - Megamare",
                'price' => 120,
                'discount_percentage' => null,
                'base_price' => 60,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Brine',
                'accords' => [
                    ['name' => '23', 'percentage' => 55],
                    ['name' => '33', 'percentage' => 50],
                    ['name' => '11', 'percentage' => 48],
                    ['name' => '35', 'percentage' => 42],
                    ['name' => '1', 'percentage' => 40],
                    ['name' => '3', 'percentage' => 39],
                    ['name' => '6', 'percentage' => 38],
                    ['name' => '14', 'percentage' => 37],
                    ['name' => '50', 'percentage' => 37],
                    ['name' => '0', 'percentage' => 36],
                ],
            ],
            [
                'name' => '109',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Louis Vuitton - City of Stars",
                'price' => 120,
                'discount_percentage' => null,
                'base_price' => 60,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Stellar',
                'accords' => [
                    ['name' => '3', 'percentage' => 55],
                    ['name' => '14', 'percentage' => 45],
                    ['name' => '13', 'percentage' => 42],
                    ['name' => '23', 'percentage' => 41],
                    ['name' => '10', 'percentage' => 40],
                ],
            ],
            [
                'name' => '110',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Tom Ford - Vanilla Sex",
                'price' => 150,
                'discount_percentage' => null,
                'base_price' => 75,
                'main_image' => 'images/zenskeboce.jpg',
                'tag' => 'Vain',
                'accords' => [
                    ['name' => '5', 'percentage' => 55],
                    ['name' => '32', 'percentage' => 48],
                    ['name' => '10', 'percentage' => 45],
                    ['name' => '29', 'percentage' => 42],
                    ['name' => '14', 'percentage' => 40],
                    ['name' => '9', 'percentage' => 39],
                    ['name' => '0', 'percentage' => 38],
                    ['name' => '2', 'percentage' => 38],
                ],
            ],
            [
                'name' => '111',
                'gender' => PerfumeGender::UNISEX,
                'inspired_by' => "Xerjoff - Alexandria II",
                'price' => 150,
                'discount_percentage' => null,
                'base_price' => 75,
                'main_image' => 'images/muskeboce.jpg',
                'tag' => 'Imperium',
                'accords' => [
                    ['name' => '0', 'percentage' => 55],
                    ['name' => '1', 'percentage' => 42],
                    ['name' => '14', 'percentage' => 41],
                    ['name' => '17', 'percentage' => 40],
                    ['name' => '40', 'percentage' => 40],
                    ['name' => '22', 'percentage' => 39],
                    ['name' => '5', 'percentage' => 38],
                    ['name' => '10', 'percentage' => 38],
                    ['name' => '45', 'percentage' => 38],
                    ['name' => '23', 'percentage' => 38],
                ],
            ],
        ];

        foreach ($perfumes as $perfume) {
            Perfume::create($perfume);
        }
    }
}
